Repository Kicchu02/Draft-Craft, pull requests merged in 2024-10, with the labels that each got.

#2 Update Project Information
  package-lock.json
  package.json
Labels: good first issue

#1 Update the Readme File
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  assets/assets.d.ts
  assets/entitlements.mac.plist
  assets/icon.icns
  assets/icon.ico
  assets/icon.png
  assets/icon.svg
  assets/icons/1024x1024.png
  assets/icons/128x128.png
  assets/icons/16x16.png
  assets/icons/24x24.png
  assets/icons/256x256.png
  assets/icons/32x32.png
  assets/icons/48x48.png
  assets/icons/512x512.png
  assets/icons/64x64.png
  assets/icons/96x96.png
  src/__tests__/App.test.tsx
Labels: documentation

#3 Create Empty Page Design
  package-lock.json
  package.json
  src/renderer/App.tsx
  src/renderer/pages/EmptyState.tsx
Labels: enhancement
